export enum AssetIssuerId {
  WorldFoundation = "world-foundation",
  Circle = "circle",
  BitGo = "bitgo",
  Universal = "universal",
  Tether = "tether",
  Ripio = "ripio",
  BiLira = "bilira",
  Coincaex = "coincaex",
}

export const assetMetadata = [
  {
    asset: "WLD",
    type: "crypto",
    network: "worldchain",
    address: "0x2cfc85d8e48f8eab294be644d9e25c3030863003",
    decimals: 18,
    symbol: "WLD",
    name: "Worldcoin",
    description:
      "Worldcoin is the first token to be globally distributed to every human.",
    primaryColor: "#181818",
    secondaryColor: "#F3F4F5",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/wld-circle.png",
    iconHexa: "https://assets.consumer.worldcoin.org/tokens/wld-hexa-v3.png",
    iconHexaV2: "https://assets.consumer.worldcoin.org/tokens/wld-hexa-v2.png",
    issuerId: AssetIssuerId.WorldFoundation,
    priceId: "WLD",
    cmcId: 13502,
    coingeckoId: "worldcoin-wld",
    dbId: "f23e13e8-0eaa-4d97-aa82-c8ba2f9421be",
    traits: {
      transferable: {},
      swappable: {
        to: [
          {
            asset: "USDCE",
            fee: 10_000n, // we use a 10_000 one-hundredth bip fee (1%) for WLD -> USDCE swaps
            maxSlippageBips: 100n,
          },
        ],
      },
    },
  },
  // VIRTUAL-SWLD represents WLD staked in the old WLD Vault (now replaced by RE7WLD)
  {
    asset: "VIRTUAL-SWLD",
    type: "crypto",
    network: "worldchain",
    // Worldchain staging address. Worldchain production address can be found in `crypto.worldchain.production.ts`.
    address: "0x1d080cb46aedc27f24b684e3d305ec401db1b5ee",
    decimals: 18,
    symbol: "WLD",
    name: "Worldcoin Vault",
    primaryColor: "#191C20",
    secondaryColor: "#E8E8E9",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/wld-vault-circle.png",
    iconHexa: "https://assets.consumer.worldcoin.org/tokens/wld-hexa-v3.png", //TODO change to actual
    iconHexaV2: "https://assets.consumer.worldcoin.org/tokens/wld-hexa-v2.png", //TODO change to actual
    priceId: "WLD",
    cmcId: 13502,
    coingeckoId: "worldcoin-wld",
    since: "2.7.5900",
    vaultFor: "WLD",
  },
  // RE7WLD represents WLD staked in the RE7WLD Morpho vault
  {
    asset: "RE7WLD",
    type: "crypto",
    network: "worldchain",
    address: "0x348831b46876d3df2db98bdec5e3b4083329ab9f",
    decimals: 18,
    symbol: "WLD",
    name: "Worldcoin Morpho Vault", // TODO change to actual
    primaryColor: "#191C20", // TODO change to actual
    secondaryColor: "#E8E8E9", // TODO change to actual
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/wld-vault-circle.png", // TODO change to actual
    iconHexa: "https://assets.consumer.worldcoin.org/tokens/wld-hexa-v3.png", //TODO change to actual
    iconHexaV2: "https://assets.consumer.worldcoin.org/tokens/wld-hexa-v2.png", //TODO change to actual
    priceId: "WLD",
    cmcId: 13502,
    coingeckoId: "worldcoin-wld",
    since: "999",
    vaultFor: "WLD",
  },
  {
    asset: "USDC",
    type: "crypto",
    network: "worldchain",
    address: "0x79a02482a880bce3f13e09da970dc34db4cd24d1",
    decimals: 6,
    symbol: "USDC",
    name: "Dollars",
    description:
      "USD Coin is a a price stable cryptocurrency backed by the US dollar.",
    primaryColor: "#00C230",
    secondaryColor: "#E6F9EC",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/usdc-circle.png",
    iconHexa: "https://assets.consumer.worldcoin.org/tokens/usdc-hexa.png",
    iconHexaV2: "https://assets.consumer.worldcoin.org/tokens/usdc-hexa-v2.png",
    cover:
      "https://assets.consumer.worldcoin.org/tokens/usdc-cover-monochromatic.png",
    issuerId: AssetIssuerId.Circle,
    displayAsset: "USD",
    priceId: "USDC",
    cmcId: 3408,
    coingeckoId: "usd-coin",
    since: "999",
  },
  // USDCE must follow after USDC
  {
    asset: "USDCE",
    type: "crypto",
    network: "worldchain",
    address: "0x79a02482a880bce3f13e09da970dc34db4cd24d1",
    decimals: 6,
    symbol: "USDC",
    name: "Dollars USDC",
    description:
      "USD Coin is a a price stable cryptocurrency backed by the US dollar.",
    primaryColor: "#00C230",
    secondaryColor: "#E6F9EC",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/usdc-circle.png?v=1",
    iconHexa: "https://assets.consumer.worldcoin.org/tokens/usdc-hexa.png",
    iconHexaV2: "https://assets.consumer.worldcoin.org/tokens/usdc-hexa-v2.png",
    cover:
      "https://assets.consumer.worldcoin.org/tokens/usdc-cover-monochromatic.png",
    flagIcon:
      "https://static.app-backend.worldcoin.dev/assets/crypto/usdc-circle.png?v=1",
    issuerId: AssetIssuerId.Circle,
    universalPairToken: "USDC",
    displayAsset: "USD",
    priceId: "USDC",
    cmcId: 3408,
    coingeckoId: "usd-coin",
    dbId: "98591778-f3d5-4feb-b027-ec55aa22f40e",
    cashFor: "USD",
    traits: {
      transferable: {},
      swappable: {},
    },
  },
  // SDAI represents USDC staked in the old USD Vault (now replaced by RE7USDC)
  {
    asset: "SDAI",
    type: "crypto",
    network: "worldchain",
    address: "0x859dbe24b90c9f2f7742083d3cf59ca41f55be5d",
    symbol: "sDAI",
    decimals: 18,
    name: "Savings",
    description:
      "Dollar savings are a way to save and earn interest on digital dollars based on the DAI Savings Rate. Terms & Conditions apply.",
    primaryColor: "#27C710",
    secondaryColor: "#00D815",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/sdai-circle.png",
    iconHexa: "https://assets.consumer.worldcoin.org/tokens/sdai-hexa.png",
    iconHexaV2: "https://assets.consumer.worldcoin.org/tokens/sdai-hexa-v2.png",
    cover: "https://assets.consumer.worldcoin.org/tokens/sdai-cover.png",
    displayAsset: "USD",
    priceId: "SDAI",
    cmcId: 28356,
    vaultFor: "USDCE",
    cashFor: "USD",
  },
  // RE7USD represents USDC staked in the RE7USDC Morpho vault
  {
    asset: "RE7USDC",
    type: "crypto",
    network: "worldchain",
    address: "0xb1e80387ebe53ff75a89736097d34dc8d9e9045b",
    decimals: 18,
    symbol: "USDC",
    name: "USDC Morpho Vault", // TODO change to actual
    primaryColor: "#00C230", // TODO change to actual
    secondaryColor: "#E6F9EC", // TODO change to actual
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/usdc-circle.png", // TODO change to actual
    iconHexa: "https://assets.consumer.worldcoin.org/tokens/usdc-hexa.png", //TODO change to actual
    iconHexaV2: "https://assets.consumer.worldcoin.org/tokens/usdc-hexa-v2.png", //TODO change to actual
    priceId: "USDC",
    cmcId: 3408,
    coingeckoId: "usd-coin",
    since: "999",
    vaultFor: "USDC",
  },
  {
    asset: "EURC",
    type: "crypto",
    network: "worldchain",
    address: "0x1c60ba0a0ed1019e8eb035e6daf4155a5ce2380b",
    decimals: 6,
    symbol: "EURC",
    name: "Digital Euros",
    description:
      "Designed to maintain 1:1 parity with the Euros, EURC is a stablecoin backed 100% by highly liquid cash and cash-equivalent assets.",
    primaryColor: "#181818",
    secondaryColor: "#FFFFFF",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/eurc.png",
    iconHexa: "https://assets.consumer.worldcoin.org/tokens/eurc-hexa.png",
    iconHexaV2: "https://assets.consumer.worldcoin.org/tokens/eurc-hexa-v2.png",
    issuerId: AssetIssuerId.Circle,
    universalPairToken: "0x1c60ba0a0ed1019e8eb035e6daf4155a5ce2380b",
    dbId: "b5bebe43-1299-4f72-a125-4e356adf7498",
    priceId: "EURC",
    cmcId: 20641,
    coingeckoId: "euro-coin",
    cashFor: "EUR",
    cashForRegions: ["EU", "AD", "XK", "MC", "ME", "SM", "VA"],
    since: "2.8.9000",
    traits: { transferable: {} },
  },
  // RE7EURC represents EURC staked in the RE7EURC Morpho vault
  {
    asset: "RE7EURC",
    type: "crypto",
    network: "worldchain",
    address: "0xdaa79e066dee8c8c15ffb37b1157f7eb8e0d1b37",
    decimals: 18,
    symbol: "EURC",
    name: "Digital Euros Morpho Vault",
    primaryColor: "#181818",
    secondaryColor: "#FFFFFF",
    priceId: "EURC",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/eurc.png",
    iconHexa: "https://assets.consumer.worldcoin.org/tokens/eurc-hexa.png",
    iconHexaV2: "https://assets.consumer.worldcoin.org/tokens/eurc-hexa-v2.png",
    cover: "https://assets.consumer.worldcoin.org/tokens/eurc-cover.png",
    vaultFor: "EURC",
    since: "999",
  },
  {
    asset: "WARS",
    type: "crypto",
    network: "worldchain",
    address: "0x0dc4f92879b7670e5f4e4e6e3c801d229129d90d",
    decimals: 18,
    symbol: "wARS",
    name: "Argentine Peso",
    description:
      "Designed to maintain 1:1 parity with the Argentine peso, wARS is 100% backed by liquid instruments denominated in Argentine pesos through a binding mechanism.",
    primaryColor: "#181818",
    secondaryColor: "#FFFFFF",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/wars.png",
    iconHexa: "https://assets.consumer.worldcoin.org/tokens/wars-hexa.png",
    iconHexaV2: "https://assets.consumer.worldcoin.org/tokens/wars-hexa-v2.png",
    issuerId: AssetIssuerId.Ripio,
    universalPairToken: "0x0dc4f92879b7670e5f4e4e6e3c801d229129d90d",
    dbId: "4965f777-b2af-50a9-adbd-c2f0bfa16a94",
    priceId: "WARS",
    fillPriceFromCurrency: "ARS",
    cashFor: "ARS",
    cashForRegions: ["AR"],
    since: "2.8.9000",
    traits: {
      transferable: {},
    },
  },
  // RE7WARS represents WARS staked in the RE7WARS Morpho vault
  {
    asset: "RE7WARS",
    type: "crypto",
    network: "worldchain",
    address: "0x1c94c7a2c71ecf13104c31f49d5138edb099d25d",
    decimals: 18,
    symbol: "WARS",
    name: "Argentine Peso Morpho Vault",
    primaryColor: "#181818",
    secondaryColor: "#FFFFFF",
    priceId: "WARS",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/wars.png",
    iconHexa: "https://assets.consumer.worldcoin.org/tokens/wars-hexa.png",
    iconHexaV2: "https://assets.consumer.worldcoin.org/tokens/wars-hexa-v2.png",
    cover: "https://assets.consumer.worldcoin.org/tokens/wars-cover.png",
    vaultFor: "WARS",
    since: "999",
  },
  {
    asset: "WCOP",
    type: "crypto",
    network: "worldchain",
    address: "0x8a1d45e102e886510e891d2ec656a708991e2d76",
    decimals: 18,
    symbol: "wCOP",
    name: "Colombian Peso",
    description:
      "Designed to maintain 1:1 parity with the Colombian peso, wCOP is 100% backed by liquid instruments denominated in Colombian pesos through a binding mechanism.",
    primaryColor: "#181818",
    secondaryColor: "#FFFFFF",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/wcop.png",
    iconHexa: "https://assets.consumer.worldcoin.org/tokens/wcop-hexa.png",
    iconHexaV2: "https://assets.consumer.worldcoin.org/tokens/wcop-hexa-v2.png",
    issuerId: AssetIssuerId.Ripio,
    universalPairToken: "0x8a1d45e102e886510e891d2ec656a708991e2d76",
    dbId: "5740834c-be51-5eaa-acfa-7ff9d11f44a7",
    priceId: "WCOP",
    fillPriceFromCurrency: "COP",
    cashFor: "COP",
    cashForRegions: ["CO"],
    since: "2.8.9000",
    traits: {
      transferable: {},
    },
  },
  {
    asset: "WMXN",
    type: "crypto",
    network: "worldchain",
    address: "0x337e7456b420bd3481e7fa61fa9850343d610d34",
    decimals: 18,
    symbol: "wMXN",
    name: "Mexican Peso",
    description:
      "Designed to maintain 1:1 parity with the Mexican peso, wMXN is 100% backed by liquid instruments denominated in Mexican pesos through a binding mechanism.",
    primaryColor: "#181818",
    secondaryColor: "#FFFFFF",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/wmxn.png",
    iconHexa: "https://assets.consumer.worldcoin.org/tokens/wmxn-hexa.png",
    iconHexaV2: "https://assets.consumer.worldcoin.org/tokens/wmxn-hexa-v2.png",
    issuerId: AssetIssuerId.Ripio,
    universalPairToken: "0x337e7456b420bd3481e7fa61fa9850343d610d34",
    dbId: "1ab16824-f8cd-5adc-85f4-e3aa6fe9c764",
    priceId: "WMXN",
    fillPriceFromCurrency: "MXN",
    cashFor: "MXN",
    cashForRegions: ["MX"],
    since: "2.8.9000",
    traits: {
      transferable: {},
    },
  },
  {
    asset: "WBRL",
    type: "crypto",
    network: "worldchain",
    address: "0xd76f5faf6888e24d9f04bf92a0c8b921fe4390e0",
    decimals: 18,
    symbol: "wBRL",
    name: "Brazilian Real",
    description:
      "Designed to maintain 1:1 parity with the Brazilian real, wBRL is 100% backed by liquid instruments denominated in Brazilian reals through a binding mechanism.",
    primaryColor: "#181818",
    secondaryColor: "#FFFFFF",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/wbrl.png",
    iconHexa: "https://assets.consumer.worldcoin.org/tokens/wbrl-hexa.png",
    iconHexaV2: "https://assets.consumer.worldcoin.org/tokens/wbrl-hexa-v2.png",
    issuerId: AssetIssuerId.Ripio,
    universalPairToken: "0xd76f5faf6888e24d9f04bf92a0c8b921fe4390e0",
    dbId: "7e84d7e5-8a7c-5541-949a-6f227ca761da",
    priceId: "WBRL",
    fillPriceFromCurrency: "BRL",
    cashFor: "BRL",
    cashForRegions: ["BR"],
    since: "2.8.9000",
    traits: {
      transferable: {},
    },
  },
  {
    asset: "WPEN",
    type: "crypto",
    network: "worldchain",
    address: "0x4f34c8b3b5fb6d98da888f0fea543d4d9c9f2ebe",
    decimals: 18,
    symbol: "wPEN",
    name: "Peruvian Sol",
    description:
      "Designed to maintain 1:1 parity with the Peruvian sol, wPEN is 100% backed by liquid instruments denominated in Peruvian soles through a binding mechanism.",
    primaryColor: "#181818",
    secondaryColor: "#FFFFFF",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/wpen.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/wpen.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/wpen.png",
    issuerId: AssetIssuerId.Ripio,
    universalPairToken: "0x4f34c8b3b5fb6d98da888f0fea543d4d9c9f2ebe",
    dbId: "8e92310c-47c8-5ce1-9158-43c6f2c63406",
    priceId: "WPEN",
    fillPriceFromCurrency: "PEN",
    cashFor: "PEN",
    cashForRegions: ["PE"],
    since: "2.8.9000",
    traits: {
      transferable: {},
    },
  },
  {
    asset: "WCLP",
    type: "crypto",
    network: "worldchain",
    address: "0x61d450a098b6a7f69fc4b98ce68198fe59768651",
    decimals: 18,
    symbol: "wCLP",
    name: "Chilean Peso",
    description:
      "Designed to maintain 1:1 parity with the Chilean peso, wCLP is 100% backed by liquid instruments denominated in Chilean pesos through a binding mechanism.",
    primaryColor: "#181818",
    secondaryColor: "#FFFFFF",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/wclp.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/wclp.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/wclp.png",
    issuerId: AssetIssuerId.Ripio,
    universalPairToken: "0x61d450a098b6a7f69fc4b98ce68198fe59768651",
    dbId: "a966a5a7-9795-5608-a50b-b23771ead02b",
    priceId: "WCLP",
    fillPriceFromCurrency: "CLP",
    cashFor: "CLP",
    cashForRegions: ["CL"],
    since: "2.8.9000",
    traits: {
      transferable: {},
    },
  },
  /*
  {
    asset: 'TRYB',
    type: 'crypto',
    network: 'worldchain',
    address: '0x2c537e5624e4af88a7ae4060c022609376c8d0eb',
    decimals: 6,
    symbol: 'TRYB',
    name: 'Turkish Lira',
    primaryColor: '#181818',
    secondaryColor: '#FFFFFF',
    icon: 'https://static.app-backend.worldcoin.dev/assets/crypto/v2/tryb.png',
    iconHexa: 'https://assets.consumer.worldcoin.org/tokens/tryb-hexa.png',
    iconHexaV2: 'https://assets.consumer.worldcoin.org/tokens/tryb-hexa-v2.png',
    issuerId: AssetIssuerId.BiLira,
    universalPairToken: '0x2c537e5624e4af88a7ae4060c022609376c8d0eb',
    dbId: 'cc924779-a0cd-5219-88a2-2ab0d0622dee',
    priceId: 'TRYB',
    fillPriceFromCurrency: 'TRY',
    cashFor: 'TRY',
    cashForRegions: ['TR'],
    since: '2.8.9000',
    traits: {
      transferable: {},
    },
  },
  {
    asset: 'POCGTQ',
    type: 'crypto',
    network: 'worldchain',
    address: '0xc03208c88cbff79a8ac4e70347d40d7bb124eea4',
    decimals: 6,
    symbol: 'POCGTQ',
    name: 'Guatemalan Quetzal',
    primaryColor: '#181818',
    secondaryColor: '#FFFFFF',
    icon: 'https://static.app-backend.worldcoin.dev/assets/crypto/v2/pocgtq.png',
    iconHexa: 'https://assets.consumer.worldcoin.org/tokens/pocgtq-hexa.png',
    iconHexaV2:
      'https://assets.consumer.worldcoin.org/tokens/pocgtq-hexa-v2.png',
    issuerId: AssetIssuerId.Coincaex,
    universalPairToken: '0xc03208c88cbff79a8ac4e70347d40d7bb124eea4',
    dbId: '4668ccc4-cf33-5164-9737-bb283a0caa86',
    priceId: 'POCGTQ',
    fillPriceFromCurrency: 'GTQ',
    cashFor: 'GTQ',
    cashForRegions: ['GT'],
    since: '2.8.9000',
    traits: {
      transferable: {},
    },
  },
  */
  {
    asset: "WETH",
    type: "crypto",
    network: "worldchain",
    address: "0x4200000000000000000000000000000000000006",
    decimals: 18,
    symbol: "WETH",
    name: "Ethereum",
    description:
      "Ethereum is community-run technology powering the cryptocurrency Ether (ETH) and thousands of decentralized applications. World App uses WETH on the World Chain Network.",
    primaryColor: "#3385FF",
    secondaryColor: "#EBF3FF",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/weth-circle.png",
    iconHexa: "https://assets.consumer.worldcoin.org/tokens/weth-hexa.png",
    iconHexaV2: "https://assets.consumer.worldcoin.org/tokens/weth-hexa-v2.png",
    cover:
      "https://assets.consumer.worldcoin.org/tokens/weth-cover-monochromatic.png",
    priceId: "ETH",
    cmcId: 1027,
    coingeckoId: "ethereum",
    dbId: "9504db0c-a2ee-44a8-a86d-007e9a411bc3",
    traits: {
      transferable: {},
      swappable: {
        to: [
          {
            asset: "USDCE",
            fee: 500n, // we use a 500 one-hundredth bip fee (0.05%) for WETH -> USDCE swaps
            maxSlippageBips: 100n,
          },
        ],
      },
    },
  },
  // RE7WETH represents WETH staked in the RE7WETH Morpho vault
  {
    asset: "RE7WETH",
    type: "crypto",
    network: "worldchain",
    address: "0x0db7e405278c2674f462ac9d9eb8b8346d1c1571",
    decimals: 18,
    symbol: "WETH",
    name: "Ethereum Morpho Vault",
    primaryColor: "#3385FF",
    secondaryColor: "#EBF3FF",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/weth-circle.png",
    iconHexa: "https://assets.consumer.worldcoin.org/tokens/weth-hexa.png",
    iconHexaV2: "https://assets.consumer.worldcoin.org/tokens/weth-hexa-v2.png",
    cover:
      "https://assets.consumer.worldcoin.org/tokens/weth-cover-monochromatic.png",
    priceId: "ETH",
    cmcId: 1027,
    coingeckoId: "ethereum",
    vaultFor: "WETH",
  },
  {
    asset: "WBTC",
    type: "crypto",
    network: "worldchain",
    address: "0x03c7054bcb39f7b2e5b2c7acb37583e32d70cfa3",
    decimals: 8,
    symbol: "WBTC",
    name: "Bitcoin",
    description:
      "Bitcoin is the world’s first cryptocurrency, introduced to the world 2009 by Satoshi. BTC is the native token of the Bitcoin network. World App uses WBTC on the World Chain Network.",
    primaryColor: "#FF5A00",
    secondaryColor: "#FFEDE6",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/wbtc-circle.png",
    iconHexa: "https://assets.consumer.worldcoin.org/tokens/wbtc-hexa.png",
    iconHexaV2: "https://assets.consumer.worldcoin.org/tokens/wbtc-hexa-v2.png",
    cover:
      "https://assets.consumer.worldcoin.org/tokens/wbtc-cover-monochromatic.png",
    issuerId: AssetIssuerId.BitGo,
    priceId: "BTC",
    cmcId: 1,
    coingeckoId: "bitcoin",
    dbId: "99db17d9-48e8-47d4-a7c0-01e5f549e7d5",
    traits: {
      transferable: {},
      swappable: {
        to: [
          {
            asset: "USDCE",
            fee: 500n, // we use a 500 one-hundredth bip fee (0.05%) for WBTC -> USDCE swaps
            maxSlippageBips: 100n,
          },
        ],
      },
    },
  },
  // RE7WBTC represents WBTC staked in the RE7WBTC Morpho vault
  {
    asset: "RE7WBTC",
    type: "crypto",
    network: "worldchain",
    address: "0xbc8c37467c5df9d50b42294b8628c25888becf61",
    decimals: 18,
    symbol: "WBTC",
    name: "Bitcoin Morpho Vault",
    primaryColor: "#FF5A00",
    secondaryColor: "#FFEDE6",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/wbtc-circle.png",
    iconHexa: "https://assets.consumer.worldcoin.org/tokens/wbtc-hexa.png",
    iconHexaV2: "https://assets.consumer.worldcoin.org/tokens/wbtc-hexa-v2.png",
    cover:
      "https://assets.consumer.worldcoin.org/tokens/wbtc-cover-monochromatic.png",
    priceId: "BTC",
    cmcId: 1,
    coingeckoId: "bitcoin",
    vaultFor: "WBTC",
  },
  {
    asset: "ULINK",
    type: "crypto",
    network: "worldchain",
    address: "0xd403d1624daef243fbcbd4a80d8a6f36affe32b2",
    decimals: 18,
    symbol: "uLINK",
    name: "Chainlink",
    description:
      "Link is the native token of the Chainlink network. uLINK is a wrapped implementation of LINK. World App supports uLINK on World Chain.",
    primaryColor: "#2A5ADA",
    secondaryColor: "#E5EBFA",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/link-circle.png",
    iconHexa: "https://assets.consumer.worldcoin.org/tokens/wbtc-hexa.png",
    iconHexaV2: "https://assets.consumer.worldcoin.org/tokens/wbtc-hexa-v2.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "86dea9c3-3dab-43a1-b937-cffe143d5c4d",
    priceId: "LINK",
    cmcId: 1975,
    coingeckoId: "chainlink",
    universalToken: "LINK",
    since: "2.8.9000",
    traits: {
      transferable: {},
      swappable: {
        to: [
          {
            asset: "USDCE",
            fee: 3_500n,
            path: ["ULINK", 3000, "WETH", 500, "USDCE"],
            maxSlippageBips: 100n,
          },
        ],
      },
    },
  },
  {
    asset: "USOL",
    type: "crypto",
    network: "worldchain",
    address: "0x9b8df6e244526ab5f6e6400d331db28c8fdddb55",
    decimals: 18,
    symbol: "uSOL",
    name: "Solana",
    description:
      "uSOL is a wrapped implementation of SOL designed to enable trading and integrations across multiple blockchains. Solana is a decentralized computing platform that uses SOL to pay for transactions. World App uses USOL on World Chain.",
    primaryColor: "#B524D0",
    secondaryColor: "#F8E9FA",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/sol-circle.png",
    iconHexa: "https://assets.consumer.worldcoin.org/tokens/wbtc-hexa.png",
    iconHexaV2: "https://assets.consumer.worldcoin.org/tokens/wbtc-hexa-v2.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "c11cbff3-1323-4762-a513-8a7c317d7be1",
    priceId: "SOL",
    cmcId: 5426,
    coingeckoId: "solana",
    universalToken: "SOL",
    since: "2.8.7900",
    traits: {
      transferable: {},
      swappable: {
        to: [
          {
            asset: "USDCE",
            fee: 3_500n,
            path: ["USOL", 3000, "WETH", 500, "USDCE"],
            maxSlippageBips: 100n,
          },
        ],
      },
    },
  },
  {
    asset: "USUI",
    type: "crypto",
    network: "worldchain",
    address: "0xb0505e5a99abd03d94a1169e638b78edfed26ea4",
    decimals: 18,
    symbol: "uSUI",
    name: "Sui",
    description:
      "USUI is a wrapped implementation of SUI designed to enable trading and integrations across multiple blockchains. Sui is a layer-1 blockchain platform created to meet the demands of global adoption, providing a secure, robust, and scalable development environment. World App uses USUI on World Chain.",
    primaryColor: "#61BFFF",
    secondaryColor: "#E6F0FF",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/sui-circle.png",
    iconHexa: "https://assets.consumer.worldcoin.org/tokens/wbtc-hexa.png",
    iconHexaV2: "https://assets.consumer.worldcoin.org/tokens/wbtc-hexa-v2.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "44458fb4-64dd-4786-b671-122a20465344",
    priceId: "SUI",
    cmcId: 20947,
    coingeckoId: "sui",
    universalToken: "SUI",
    since: "2.8.7900",
    traits: {
      transferable: {},
      swappable: {
        to: [
          {
            asset: "USDCE",
            fee: 3_500n,
            path: ["USUI", 3000, "WETH", 500, "USDCE"],
            maxSlippageBips: 100n,
          },
        ],
      },
    },
  },
  {
    asset: "UDOGE",
    type: "crypto",
    network: "worldchain",
    address: "0x12e96c2bfea6e835cf8dd38a5834fa61cf723736",
    decimals: 18,
    symbol: "uDOGE",
    name: "Dogecoin",
    description:
      "uDOGE is a wrapped implementation of DOGE designed to enable trading and integrations across multiple blockchains. Dogecoin (DOGE) was created as a lighthearted alternative to traditional cryptocurrencies like Bitcoin in 2013. World App uses UDOGE on World Chain.",
    primaryColor: "#988430",
    secondaryColor: "#F8F5E8",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/doge-circle.png",
    iconHexa: "https://assets.consumer.worldcoin.org/tokens/wbtc-hexa.png",
    iconHexaV2: "https://assets.consumer.worldcoin.org/tokens/wbtc-hexa-v2.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "a1996cf9-4d3d-4691-b5d1-f0b841aec048",
    priceId: "DOGE",
    cmcId: 74,
    coingeckoId: "dogecoin",
    universalToken: "DOGE",
    since: "2.8.7900",
    traits: {
      transferable: {},
      swappable: {
        to: [
          {
            asset: "USDCE",
            fee: 3_500n,
            path: ["UDOGE", 3000, "WETH", 500, "USDCE"],
            maxSlippageBips: 100n,
          },
        ],
      },
    },
  },
  {
    asset: "UXRP",
    type: "crypto",
    network: "worldchain",
    address: "0x2615a94df961278dcbc41fb0a54fec5f10a693ae",
    decimals: 18,
    symbol: "uXRP",
    name: "XRP",
    description:
      "uXRP is a wrapped implementation of XRP designed to enable trading and integrations across multiple blockchains. XRP is the native token of the XRP Ledger, and the cryptocurrency used by the Ripple payment network. Built for enterprise use on a global scale, XRP powers cost-efficient cross-border payments. World App uses UXRP on World Chain.",
    primaryColor: "#23292F",
    secondaryColor: "#E9EAEA",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/xrp-circle.png",
    iconHexa: "https://assets.consumer.worldcoin.org/tokens/wbtc-hexa.png",
    iconHexaV2: "https://assets.consumer.worldcoin.org/tokens/wbtc-hexa-v2.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "2ba99531-8842-41fb-897e-c07353816de4",
    priceId: "XRP",
    cmcId: 52,
    coingeckoId: "ripple",
    universalToken: "XRP",
    since: "2.8.7900",
    traits: {
      transferable: {},
      swappable: {
        to: [
          {
            asset: "USDCE",
            fee: 3_500n,
            path: ["UXRP", 3000, "WETH", 500, "USDCE"],
            maxSlippageBips: 100n,
          },
        ],
      },
    },
  },
  {
    asset: "UXLM",
    type: "crypto",
    network: "worldchain",
    address: "0x378c326a472915d38b2d8d41e1345987835fab64",
    decimals: 18,
    symbol: "uXLM",
    name: "Stellar",
    description:
      "Stellar is the native token that powers the Stellar payment network. uXLM is a wrapped implementation of XLM. World App supports uXLM on World Chain.",
    primaryColor: "#000000",
    secondaryColor: "#E9EAEA",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/xlm-circle.png",
    iconHexa: "https://assets.consumer.worldcoin.org/tokens/wbtc-hexa.png",
    iconHexaV2: "https://assets.consumer.worldcoin.org/tokens/wbtc-hexa-v2.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "3db0b03a-8ac5-4fb3-95d0-2a0ae146f93a",
    priceId: "XLM",
    cmcId: 512,
    universalToken: "XLM",
    since: "2.8.9000",
    traits: {
      transferable: {},
      swappable: {
        to: [
          {
            asset: "USDCE",
            fee: 3_500n,
            path: ["UXLM", 3000, "WETH", 500, "USDCE"],
            maxSlippageBips: 100n,
          },
        ],
      },
    },
  },
  {
    asset: "ULTC",
    type: "crypto",
    network: "worldchain",
    address: "0x3eb097375fc2fc361e4a472f5e7067238c547c52",
    decimals: 18,
    symbol: "uLTC",
    name: "Litecoin",
    description:
      "Litecoin is the native token of the Litecoin blockchain platform. uLTC is a wrapped implementation of LTC. World App supports uLTC on World Chain.",
    primaryColor: "#27549A",
    secondaryColor: "#E9EAEA",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/ltc-circle.png",
    iconHexa: "https://assets.consumer.worldcoin.org/tokens/wbtc-hexa.png",
    iconHexaV2: "https://assets.consumer.worldcoin.org/tokens/wbtc-hexa-v2.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "193442f3-eaa1-4abe-9232-d1e3eea62231",
    priceId: "LTC",
    cmcId: 2,
    universalToken: "LTC",
    since: "2.8.9000",
    traits: {
      transferable: {},
      swappable: {
        to: [
          {
            asset: "USDCE",
            fee: 3_500n,
            path: ["ULTC", 3000, "WETH", 500, "USDCE"],
            maxSlippageBips: 100n,
          },
        ],
      },
    },
  },
  {
    asset: "USHIB",
    type: "crypto",
    network: "worldchain",
    address: "0x239b9c1f24f3423062b0d364796e07ee905e9fce",
    decimals: 18,
    symbol: "uSHIB",
    name: "Shiba Inu",
    description:
      "Shib is a decentralized cryptocurrency inspired by the Shiba Inu dog breed. uSHIB is a wrapped implementation of SHIB. World App supports uSHIB on World Chain.",
    primaryColor: "#FFA409",
    secondaryColor: "#E9EAEA",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/shib-circle.png",
    iconHexa: "https://assets.consumer.worldcoin.org/tokens/wbtc-hexa.png",
    iconHexaV2: "https://assets.consumer.worldcoin.org/tokens/wbtc-hexa-v2.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "c830eaea-db74-4411-a8db-26130e12098f",
    priceId: "SHIB",
    cmcId: 5994,
    universalToken: "SHIB",
    since: "2.8.9000",
    traits: {
      transferable: {},
      swappable: {
        to: [
          {
            asset: "USDCE",
            fee: 3_500n,
            path: ["USHIB", 3000, "WETH", 500, "USDCE"],
            maxSlippageBips: 100n,
          },
        ],
      },
    },
  },
  {
    asset: "UADA",
    type: "crypto",
    network: "worldchain",
    address: "0xa3a34a0d9a08ccddb6ed422ac0a28a06731335aa",
    decimals: 18,
    symbol: "uADA",
    name: "Cardano",
    description:
      "Cardano is the native token of the Cardano blockchain platform. uADA is a wrapped implementation of ADA. World App supports uADA on World Chain.",
    primaryColor: "#0033AD",
    secondaryColor: "#E9EAEA",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/ada-circle.png",
    iconHexa: "https://assets.consumer.worldcoin.org/tokens/wbtc-hexa.png",
    iconHexaV2: "https://assets.consumer.worldcoin.org/tokens/wbtc-hexa-v2.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "b747f8f3-ee5e-4e69-9d96-671ef81f3098",
    priceId: "ADA",
    cmcId: 2010,
    universalToken: "ADA",
    since: "2.8.9000",
    traits: {
      transferable: {},
      swappable: {
        to: [
          {
            asset: "USDCE",
            fee: 3_500n,
            path: ["UADA", 3000, "WETH", 500, "USDCE"],
            maxSlippageBips: 100n,
          },
        ],
      },
    },
  },
  {
    asset: "ORO",
    type: "crypto",
    network: "worldchain",
    address: "0xcd1e32b86953d79a6ac58e813d2ea7a1790cab63",
    decimals: 18,
    symbol: "ORO",
    name: "ORO",
    description:
      "ORO is a token on World Chain. ORO can also be claimed in the ORO Mini App.",
    primaryColor: "#FEC400",
    secondaryColor: "#E9EAEA",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/oro-circle.png",
    iconHexa: "https://assets.consumer.worldcoin.org/tokens/wbtc-hexa.png",
    iconHexaV2: "https://assets.consumer.worldcoin.org/tokens/wbtc-hexa-v2.png",
    dbId: "120a5475-80cb-4a87-bb66-4b6c167d0d24",
    priceId: "ORO",
    fillPriceFromZapper: true,
    since: "2.8.9000",
    traits: {
      transferable: {},
      swappable: {
        to: [
          {
            asset: "USDCE",
            fee: 10_000n,
            maxSlippageBips: 100n,
          },
        ],
      },
    },
  },
  {
    asset: "ORB",
    type: "crypto",
    network: "worldchain",
    address: "0xf3f92a60e6004f3982f0fde0d43602fc0a30a0db",
    decimals: 18,
    symbol: "ORB",
    name: "Orb",
    description:
      "ORB is a token on World Chain. Orb can also be claimed in the Orb Mini App.",
    primaryColor: "#181818",
    secondaryColor: "#E9EAEA",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/orb-circle.png",
    iconHexa: "https://assets.consumer.worldcoin.org/tokens/wbtc-hexa.png",
    iconHexaV2: "https://assets.consumer.worldcoin.org/tokens/wbtc-hexa-v2.png",
    dbId: "fd468b4f-62a7-46ea-997e-9d9a74757a3b",
    priceId: "ORB",
    fillPriceFromZapper: true,
    since: "2.8.9000",
    traits: {
      transferable: {},
      swappable: {
        to: [
          {
            asset: "USDCE",
            fee: 10_000n,
            maxSlippageBips: 100n,
          },
        ],
      },
    },
  },
  {
    asset: "OXAUT",
    type: "crypto",
    network: "worldchain",
    address: "0x30974f73a4ac9e606ed80da928e454977ac486d2",
    decimals: 6,
    symbol: "oXAUt",
    name: "Tether Gold",
    description:
      "Tether Gold is a digital token backed by physical gold. oXAUt is a wrapped implementation of XAUT. World App supports oXAUt on World Chain.",
    primaryColor: "#CD980F",
    secondaryColor: "#E9EAEA",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/xaut-circle.png",
    iconHexa: "https://assets.consumer.worldcoin.org/tokens/wbtc-hexa.png",
    iconHexaV2: "https://assets.consumer.worldcoin.org/tokens/wbtc-hexa-v2.png",
    issuerId: AssetIssuerId.Tether,
    dbId: "2839d440-38b0-4393-a1f0-5a8abd70888c",
    priceId: "XAUt",
    cmcId: 5176,
    coingeckoId: "tether-gold",
    since: "2.8.9000",
    traits: {
      transferable: {},
      swappable: {
        to: [
          {
            asset: "USDCE",
            fee: 3_000n,
            maxSlippageBips: 100n,
          },
        ],
      },
    },
  },
  {
    asset: "UALGO",
    type: "crypto",
    network: "worldchain",
    address: "0x3a51f2a377ea8b55faf3c671138a00503b031af3",
    decimals: 18,
    symbol: "uALGO",
    name: "Algorand",
    description: "World App supports uALGO on World Chain.",
    primaryColor: "#17CAC6",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ualgo.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ualgo.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ualgo.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "9fc1d1f5-f72b-5b6a-8ca4-40c1e098a3c7",
    priceId: "ALGO",
    cmcId: 4030,
    universalToken: "ALGO",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UBCH",
    type: "crypto",
    network: "worldchain",
    address: "0x7be0cc2cadcd4a8f9901b4a66244dcdd9bd02e0f",
    decimals: 18,
    symbol: "uBCH",
    name: "Bitcoin Cash",
    description: "World App supports uBCH on World Chain.",
    primaryColor: "#0AC18E",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ubch.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ubch.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ubch.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "8fe636df-2c84-5957-a65a-2d6db44df536",
    priceId: "BCH",
    cmcId: 1831,
    universalToken: "BCH",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UDOT",
    type: "crypto",
    network: "worldchain",
    address: "0x0f813f4785b2360009f9ac9bf6121a85f109efc6",
    decimals: 18,
    symbol: "uDOT",
    name: "Polkadot",
    description: "World App supports uDOT on World Chain.",
    primaryColor: "#E6007A",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/udot.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/udot.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/udot.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "0da34dc0-4e5a-597d-a812-46f7b7b84934",
    priceId: "DOT",
    cmcId: 6636,
    universalToken: "DOT",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UNEAR",
    type: "crypto",
    network: "worldchain",
    address: "0x5ed25e305e08f58afd7995eac72563e6be65a617",
    decimals: 18,
    symbol: "uNEAR",
    name: "NEAR",
    description: "World App supports uNEAR on World Chain.",
    primaryColor: "#00EC97",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/unear.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/unear.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/unear.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "e886ccd6-0acd-5899-85db-4a85ea5b1dde",
    priceId: "NEAR",
    cmcId: 6535,
    universalToken: "NEAR",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UAVAX",
    type: "crypto",
    network: "worldchain",
    address: "0xd6a34b430c05ac78c24985f8abee2616bc1788cb",
    decimals: 18,
    symbol: "uAVAX",
    name: "Avalanche",
    description: "World App supports uAVAX on World Chain.",
    primaryColor: "#E84142",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uavax.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uavax.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uavax.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "ead4f3de-ba48-5048-bed8-b41ad32fcb56",
    priceId: "AVAX",
    cmcId: 5805,
    universalToken: "AVAX",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UPOL",
    type: "crypto",
    network: "worldchain",
    address: "0xd76d45358b79564817aa87f02f3b85338b96f06a",
    decimals: 18,
    symbol: "uPOL",
    name: "Polygon",
    description: "World App supports uPOL on World Chain.",
    primaryColor: "#6C00F6",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/upol.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/upol.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/upol.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "ac019fda-9d55-5f2a-97ff-508782d9cc2f",
    priceId: "POL",
    cmcId: 28321,
    universalToken: "POL",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UUNI",
    type: "crypto",
    network: "worldchain",
    address: "0xfb3cb973b2a9e2e09746393c59e7fb0d5189d290",
    decimals: 18,
    symbol: "uUNI",
    name: "Uniswap",
    description: "World App supports uUNI on World Chain.",
    primaryColor: "#FF007A",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uuni.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uuni.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uuni.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "0544bc95-7d6c-5775-ad2c-3f2618420f13",
    priceId: "UNI",
    cmcId: 7083,
    universalToken: "UNI",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UAPT",
    type: "crypto",
    network: "worldchain",
    address: "0x9c0e042d65a2e1ff31ac83f404e5cb79f452c337",
    decimals: 18,
    symbol: "uAPT",
    name: "Aptos",
    description: "World App supports uAPT on World Chain.",
    primaryColor: "#000000",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uapt.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uapt.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uapt.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "f758a390-cf2b-5772-a8b1-0d94e84362a5",
    priceId: "APT",
    cmcId: 21794,
    universalToken: "APT",
    since: "2.9.306",
    traits: { transferable: {} },
  },
  {
    asset: "USTX",
    type: "crypto",
    network: "worldchain",
    address: "0x4b92ea5a2602fba275150db4201a6047056f6913",
    decimals: 18,
    symbol: "uSTX",
    name: "Stacks",
    description: "World App supports uSTX on World Chain.",
    primaryColor: "#FC6432",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ustx.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ustx.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ustx.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "792732da-0cca-50de-a357-9d73e3f4a1b5",
    priceId: "STX",
    cmcId: 4847,
    universalToken: "STX",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UMKR",
    type: "crypto",
    network: "worldchain",
    address: "0x30f16e3273ab6e4584b79b76fd944e577e49a5c8",
    decimals: 18,
    symbol: "uMKR",
    name: "Maker",
    description: "World App supports uMKR on World Chain.",
    primaryColor: "#54AFA0",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/umkr.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/umkr.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/umkr.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "1d31b779-44ef-5b79-afd9-fc4c016adab7",
    priceId: "MKR",
    cmcId: 1518,
    universalToken: "MKR",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "URNDR",
    type: "crypto",
    network: "worldchain",
    address: "0xa260ba5fd9ff3fae55ac4930165a9c33519de694",
    decimals: 18,
    symbol: "uRNDR",
    name: "Render",
    description: "World App supports uRNDR on World Chain.",
    primaryColor: "#CF1011",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/urndr.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/urndr.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/urndr.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "25c99f36-8314-5c5a-afb8-68f330402eb6",
    priceId: "RENDER",
    cmcId: 5690,
    universalToken: "RNDR",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "USEI",
    type: "crypto",
    network: "worldchain",
    address: "0x71a67215a2025f501f386a49858a9ced2fc0249d",
    decimals: 18,
    symbol: "uSEI",
    name: "Sei",
    description: "World App supports uSEI on World Chain.",
    primaryColor: "#0B2632",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/usei.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/usei.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/usei.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "4f739d61-3da0-59ef-95c2-a45743adef00",
    priceId: "SEI",
    cmcId: 23149,
    universalToken: "SEI",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UPEPE",
    type: "crypto",
    network: "worldchain",
    address: "0xe5c436b0a34df18f1dae98af344ca5122e7d57c4",
    decimals: 18,
    symbol: "uPEPE",
    name: "Pepe",
    description: "World App supports uPEPE on World Chain.",
    primaryColor: "#3D8130",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/upepe.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/upepe.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/upepe.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "d8a7421a-5270-56fc-9073-fd60ae77ea11",
    priceId: "PEPE",
    cmcId: 24478,
    universalToken: "PEPE",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UTRUMP",
    type: "crypto",
    network: "worldchain",
    address: "0x8ccf84de79df699a373421c769f1900aa71200b0",
    decimals: 18,
    symbol: "uTRUMP",
    name: "Trump",
    description: "World App supports uTRUMP on World Chain.",
    primaryColor: "#181818",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/utrump.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/utrump.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/utrump.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "ebe3113e-54c0-59f0-a56c-71720cbc0025",
    priceId: "TRUMP",
    priceSince: new Date("2025-01-18T02:05:00.000Z"),
    cmcId: 35336,
    universalToken: "TRUMP",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UHBAR",
    type: "crypto",
    network: "worldchain",
    address: "0xc79e06860aa9564f95e08fb7e5b61458d0c63898",
    decimals: 18,
    symbol: "uHBAR",
    name: "Hedera",
    description: "World App supports uHBAR on World Chain.",
    primaryColor: "#000000",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uhbar.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uhbar.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uhbar.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "281b4630-e105-5c89-8064-86916f655d1d",
    priceId: "HBAR",
    cmcId: 4642,
    universalToken: "HBAR",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UICP",
    type: "crypto",
    network: "worldchain",
    address: "0x40318ee213227894b5316e5ec84f6a5caf3bbedd",
    decimals: 18,
    symbol: "uICP",
    name: "Internet Computer",
    description: "World App supports uICP on World Chain.",
    primaryColor: "#29ABE2",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uicp.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uicp.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uicp.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "658fcd3d-eee9-5200-9f1b-8377eadc6810",
    priceId: "ICP",
    cmcId: 8916,
    universalToken: "ICP",
    since: "2.9.306",
    traits: { transferable: {} },
  },
  {
    asset: "UAAVE",
    type: "crypto",
    network: "worldchain",
    address: "0xf383074c4b993d1ccd196188d27d0ddf22ad463c",
    decimals: 18,
    symbol: "uAAVE",
    name: "Aave",
    description: "World App supports uAAVE on World Chain.",
    primaryColor: "#9391F7",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uaave.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uaave.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uaave.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "e760db27-36e8-52b1-9e4f-ad1c3f94ca78",
    priceId: "AAVE",
    cmcId: 7278,
    universalToken: "AAVE",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UETC",
    type: "crypto",
    network: "worldchain",
    address: "0xd61bcf79b26787ae993f75b064d2e3b3cc738c5d",
    decimals: 18,
    symbol: "uETC",
    name: "Ethereum Classic",
    description: "World App supports uETC on World Chain.",
    primaryColor: "#429426",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uetc.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uetc.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uetc.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "cc1181ec-9c3d-5ef3-b53a-043ac315779e",
    priceId: "ETC",
    cmcId: 1321,
    universalToken: "ETC",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UFET",
    type: "crypto",
    network: "worldchain",
    address: "0xacbf16f82753f3d52a2c87e4eeda220c9a7a3762",
    decimals: 18,
    symbol: "uFET",
    name: "Artificial Superintelligence Alliance",
    description: "World App supports uFET on World Chain.",
    primaryColor: "#000000",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ufet.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ufet.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ufet.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "81d3460f-0ee6-5156-8515-eeeaaf882c03",
    priceId: "FET",
    cmcId: 3773,
    universalToken: "FET",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UATOM",
    type: "crypto",
    network: "worldchain",
    address: "0x6e934283dae5d5d1831cbe8d557c44c9b83f30ee",
    decimals: 18,
    symbol: "uATOM",
    name: "Cosmos",
    description: "World App supports uATOM on World Chain.",
    primaryColor: "#2E3148",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uatom.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uatom.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uatom.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "e95a8c64-514c-556a-8de4-7c227db32be7",
    priceId: "ATOM",
    cmcId: 3794,
    universalToken: "ATOM",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UINJ",
    type: "crypto",
    network: "worldchain",
    address: "0xdb18fb11db1b972a54bd89ce04bad61855c07788",
    decimals: 18,
    symbol: "uINJ",
    name: "Injective",
    description: "World App supports uINJ on World Chain.",
    primaryColor: "#4C3DFF",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uinj.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uinj.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uinj.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "b86a1531-d82d-5329-8e9f-9dc13fa14c94",
    priceId: "INJ",
    cmcId: 7226,
    universalToken: "INJ",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UIMX",
    type: "crypto",
    network: "worldchain",
    address: "0x0935b271ca903ada3ffe1ac1353fc4a49e7ee87b",
    decimals: 18,
    symbol: "uIMX",
    name: "Immutable",
    description: "World App supports uIMX on World Chain.",
    primaryColor: "#000000",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uimx.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uimx.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uimx.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "6a45ba39-a28f-5dd0-82a8-ed91d18de9a4",
    priceId: "IMX",
    cmcId: 10603,
    universalToken: "IMX",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UGRT",
    type: "crypto",
    network: "worldchain",
    address: "0x3d00283af5ab11ee7f6ec51573ab62b6fb6dfd8f",
    decimals: 18,
    symbol: "uGRT",
    name: "The Graph",
    description: "World App supports uGRT on World Chain.",
    primaryColor: "#6747ED",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ugrt.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ugrt.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ugrt.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "162e3dfb-8a16-508f-883a-56d5be1de54d",
    priceId: "GRT",
    cmcId: 6719,
    universalToken: "GRT",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UJASMY",
    type: "crypto",
    network: "worldchain",
    address: "0x8989377fd349adfa99e6ce3cb6c0d148dfc7f19e",
    decimals: 18,
    symbol: "uJASMY",
    name: "JasmyCoin",
    description: "World App supports uJASMY on World Chain.",
    primaryColor: "#F7941C",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ujasmy.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ujasmy.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ujasmy.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "8796dd72-1527-584b-9e27-91301bf34df2",
    priceId: "JASMY",
    cmcId: 8425,
    universalToken: "JASMY",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "ULDO",
    type: "crypto",
    network: "worldchain",
    address: "0x135ff404ba56e167f58bc664156beaa0a0fd95ac",
    decimals: 18,
    symbol: "uLDO",
    name: "Lido DAO",
    description: "World App supports uLDO on World Chain.",
    primaryColor: "#EE9584",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uldo.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uldo.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uldo.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "b89eff0b-3823-58f0-ab56-c7d197825ebc",
    priceId: "LDO",
    cmcId: 8000,
    universalToken: "LDO",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UQNT",
    type: "crypto",
    network: "worldchain",
    address: "0x893adcbdc7fcfa0ebb6d3803f01df1ec199bf7c5",
    decimals: 18,
    symbol: "uQNT",
    name: "Quant",
    description: "World App supports uQNT on World Chain.",
    primaryColor: "#000000",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uqnt.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uqnt.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uqnt.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "ad35a839-a3d5-56c7-8dce-b5387336aef8",
    priceId: "QNT",
    cmcId: 3155,
    universalToken: "QNT",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "USAND",
    type: "crypto",
    network: "worldchain",
    address: "0x1b94330eec66ba458a51b0b14f411910d5f678d0",
    decimals: 18,
    symbol: "uSAND",
    name: "The Sandbox",
    description: "World App supports uSAND on World Chain.",
    primaryColor: "#0099F7",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/usand.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/usand.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/usand.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "25c5275b-fd92-5cfa-8fe2-f09ad474ac98",
    priceId: "SAND",
    cmcId: 6210,
    universalToken: "SAND",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UXTZ",
    type: "crypto",
    network: "worldchain",
    address: "0xd7d5c59457d66fe800dba22b35e9c6c379d64499",
    decimals: 18,
    symbol: "uXTZ",
    name: "Tezos",
    description: "World App supports uXTZ on World Chain.",
    primaryColor: "#2C7DF7",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uxtz.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uxtz.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uxtz.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "efee261b-c1d0-540d-aa5a-9e0aaa1da01b",
    priceId: "XTZ",
    cmcId: 2011,
    universalToken: "XTZ",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UHNT",
    type: "crypto",
    network: "worldchain",
    address: "0x05f191a4aac4b358ab99db3a83a8f96216ecb274",
    decimals: 18,
    symbol: "uHNT",
    name: "Helium",
    description: "World App supports uHNT on World Chain.",
    primaryColor: "#474DFF",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uhnt.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uhnt.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uhnt.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "d847614c-3cd0-5fc5-9813-d19189f164dc",
    priceId: "HNT",
    cmcId: 5665,
    universalToken: "HNT",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UAXS",
    type: "crypto",
    network: "worldchain",
    address: "0x5a03841c2e2f5811f9e548cf98e88e878e55d99e",
    decimals: 18,
    symbol: "uAXS",
    name: "Axie Infinity",
    description: "World App supports uAXS on World Chain.",
    primaryColor: "#0055D5",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uaxs.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uaxs.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uaxs.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "a3d74dac-5572-5ca5-b9eb-48e9dd88cf0d",
    priceId: "AXS",
    cmcId: 6783,
    universalToken: "AXS",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UMANA",
    type: "crypto",
    network: "worldchain",
    address: "0x508e751fdcf144910074cc817a16757f608db52a",
    decimals: 18,
    symbol: "uMANA",
    name: "Decentraland",
    description: "World App supports uMANA on World Chain.",
    primaryColor: "#FF7458",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/umana.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/umana.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/umana.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "90b9e28c-0aa9-53a9-bf5f-7b78a4052c3e",
    priceId: "MANA",
    cmcId: 1966,
    universalToken: "MANA",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UEGLD",
    type: "crypto",
    network: "worldchain",
    address: "0x16275fd42439a6671b188bdc3949a5ec61932c48",
    decimals: 18,
    symbol: "uEGLD",
    name: "MultiversX",
    description: "World App supports uEGLD on World Chain.",
    primaryColor: "#23F7DD",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uegld.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uegld.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uegld.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "1c91c50e-76b3-5a06-b3f4-4d1a70f8a476",
    priceId: "EGLD",
    cmcId: 6892,
    universalToken: "EGLD",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UAPE",
    type: "crypto",
    network: "worldchain",
    address: "0x9af46f95a0a8be5c2e0a0274a8b153c72d617e85",
    decimals: 18,
    symbol: "uAPE",
    name: "ApeCoin",
    description: "World App supports uAPE on World Chain.",
    primaryColor: "#073183",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uape.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uape.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uape.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "a6c4d9d7-c7bf-599f-9b9f-ce1f740f199d",
    priceId: "APE",
    cmcId: 18876,
    universalToken: "APE",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UZEC",
    type: "crypto",
    network: "worldchain",
    address: "0x83f31af747189c2fa9e5deb253200c505eff6ed2",
    decimals: 18,
    symbol: "uZEC",
    name: "Zcash",
    description: "World App supports uZEC on World Chain.",
    primaryColor: "#ECB244",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uzec.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uzec.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uzec.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "fd6c07fe-d020-5153-8bc6-d295f2aa5c3e",
    priceId: "ZEC",
    cmcId: 1437,
    universalToken: "ZEC",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UCHZ",
    type: "crypto",
    network: "worldchain",
    address: "0xc5cdeb649ed1a7895b935acc8eb5aa0d7a8492be",
    decimals: 18,
    symbol: "uCHZ",
    name: "Chiliz",
    description: "World App supports uCHZ on World Chain.",
    primaryColor: "#FF014A",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uchz.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uchz.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uchz.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "4b65a486-1922-5461-9155-9d75847a86fd",
    priceId: "CHZ",
    cmcId: 4066,
    universalToken: "CHZ",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UMINA",
    type: "crypto",
    network: "worldchain",
    address: "0xd6a746236f15e18053dd3ae8c27341b44cb08e59",
    decimals: 18,
    symbol: "uMINA",
    name: "Mina",
    description: "World App supports uMINA on World Chain.",
    primaryColor: "#2D2D2D",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/umina.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/umina.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/umina.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "88b972ea-33f3-5123-bcc6-0dd801882722",
    priceId: "MINA",
    cmcId: 8646,
    universalToken: "MINA",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UROSE",
    type: "crypto",
    network: "worldchain",
    address: "0x3ecb91ac996e8c55fe1835969a4967f95a07ca71",
    decimals: 18,
    symbol: "uROSE",
    name: "Oasis Network",
    description: "World App supports uROSE on World Chain.",
    primaryColor: "#0500E2",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/urose.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/urose.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/urose.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "5220eeaf-edd3-58fe-8f11-9169dfb72ff5",
    priceId: "ROSE",
    cmcId: 7653,
    universalToken: "ROSE",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "ULPT",
    type: "crypto",
    network: "worldchain",
    address: "0xe3ae3ee16a89973d67b678aad2c3be865dcc6880",
    decimals: 18,
    symbol: "uLPT",
    name: "Livepeer",
    description: "World App supports uLPT on World Chain.",
    primaryColor: "#30A46C",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ulpt.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ulpt.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ulpt.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "3e2ce96b-d22b-5cc0-bd37-c4cebbd00ca0",
    priceId: "LPT",
    cmcId: 3640,
    universalToken: "LPT",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UKSM",
    type: "crypto",
    network: "worldchain",
    address: "0x2f2041c267795a85b0de04443e7b947a6234fee8",
    decimals: 18,
    symbol: "uKSM",
    name: "Kusama",
    description: "World App supports uKSM on World Chain.",
    primaryColor: "#000000",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uksm.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uksm.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uksm.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "e507a60d-ec46-5d41-aca9-e4f5a078a515",
    priceId: "KSM",
    cmcId: 5034,
    universalToken: "KSM",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UBLUR",
    type: "crypto",
    network: "worldchain",
    address: "0x44951c66dfe920baed34457a2cfa65a0c7ff2025",
    decimals: 18,
    symbol: "uBLUR",
    name: "Blur",
    description: "World App supports uBLUR on World Chain.",
    primaryColor: "#F96D2A",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ublur.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ublur.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ublur.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "4665b91e-bbd5-5fc3-a42b-64a1a2e63f9f",
    priceId: "BLUR",
    cmcId: 23121,
    universalToken: "BLUR",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UZK",
    type: "crypto",
    network: "worldchain",
    address: "0x3a6b4b4f2250b8cce56ced4ca286a2ebe6f479a2",
    decimals: 18,
    symbol: "uZK",
    name: "ZKsync",
    description: "World App supports uZK on World Chain.",
    primaryColor: "#11141A",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uzk.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uzk.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uzk.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "3d4383d3-a1c5-5beb-bd8a-f21f28b4f10f",
    priceId: "ZK",
    cmcId: 24091,
    universalToken: "ZK",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UVET",
    type: "crypto",
    network: "worldchain",
    address: "0x1b0dcc586323c0e10f8be72ecc104048f25fd625",
    decimals: 18,
    symbol: "uVET",
    name: "VeChain",
    description: "World App supports uVET on World Chain.",
    primaryColor: "#6041DD",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uvet.png?v=1",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uvet.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uvet.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "31fa45d4-f7ea-52fa-8b1e-d149f32598b6",
    priceId: "VET",
    cmcId: 3077,
    universalToken: "VET",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "USNX",
    type: "crypto",
    network: "worldchain",
    address: "0x444fa322da64a49a32d29ccd3a1f4df3de25cf52",
    decimals: 18,
    symbol: "uSNX",
    name: "Synthetix",
    description: "World App supports uSNX on World Chain.",
    primaryColor: "#00D1FF",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/usnx.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/usnx.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/usnx.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "433426d6-ae84-5553-92b6-0ee8e4950898",
    priceId: "SNX",
    cmcId: 2586,
    universalToken: "SNX",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UGMT",
    type: "crypto",
    network: "worldchain",
    address: "0x6ca225ae2c92c8a7e9c3162cfcaaa55ad0b09701",
    decimals: 18,
    symbol: "uGMT",
    name: "STEPN",
    description: "World App supports uGMT on World Chain.",
    primaryColor: "#E6BC7B",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ugmt.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ugmt.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ugmt.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "ebbaf573-c441-5f91-9fd8-19510b247b2f",
    priceId: "GMT",
    cmcId: 18069,
    universalToken: "GMT",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "USTRK",
    type: "crypto",
    network: "worldchain",
    address: "0xd045be6ab98d17a161cfcfc118a8b428d70543ff",
    decimals: 18,
    symbol: "uSTRK",
    name: "Starknet",
    description: "World App supports uSTRK on World Chain.",
    primaryColor: "#0C0C4F",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ustrk.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ustrk.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ustrk.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "4d061faf-a49e-5209-aef4-66843dd459d8",
    priceId: "STRK",
    cmcId: 22691,
    universalToken: "STRK",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UPNUT",
    type: "crypto",
    network: "worldchain",
    address: "0x6814e4be03aeb33fe135fe0e85ca6b0a03247519",
    decimals: 18,
    symbol: "uPNUT",
    name: "Peanut the Squirrel",
    description: "World App supports uPNUT on World Chain.",
    primaryColor: "#6B3415",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/upnut.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/upnut.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/upnut.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "363f9118-4b47-5fad-802e-e205ff5c698c",
    priceId: "PNUT",
    cmcId: 33788,
    universalToken: "PNUT",
    since: "2.8.7900",
    traits: {
      transferable: {},
      swappable: {
        to: [
          {
            asset: "USDCE",
            fee: 3_500n,
            path: ["UPNUT", 3000, "WETH", 500, "USDCE"],
            maxSlippageBips: 100n,
          },
        ],
      },
    },
  },
  {
    asset: "UOP",
    type: "crypto",
    network: "worldchain",
    address: "0x2198b777d5cb8cd5aa01d5c4d70f8f28fed9bc05",
    decimals: 18,
    symbol: "uOP",
    name: "Optimism",
    description: "World App supports uOP on World Chain.",
    primaryColor: "#FF0420",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uop.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uop.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uop.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "735480ef-8895-58b6-9112-5c5622d61ad5",
    priceId: "OP",
    cmcId: 11840,
    universalToken: "OP",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UONDO",
    type: "crypto",
    network: "worldchain",
    address: "0x90131d95a9a5b48b6a3ee0400807248becf4b7a4",
    decimals: 18,
    symbol: "uONDO",
    name: "Ondo",
    description: "World App supports uONDO on World Chain.",
    primaryColor: "#06070A",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uondo.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uondo.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uondo.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "92cdf484-2bd4-59bb-8ca7-242cb3b44d37",
    priceId: "ONDO",
    cmcId: 21159,
    universalToken: "ONDO",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UJTO",
    type: "crypto",
    network: "worldchain",
    address: "0xfdf116c8bef1d4060e4117092298abff80b170ca",
    decimals: 18,
    symbol: "uJTO",
    name: "Jito",
    description: "World App supports uJTO on World Chain.",
    primaryColor: "#000000",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ujto.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ujto.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ujto.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "13f0fa67-f8f4-5743-a4f6-7672ad93491e",
    priceId: "JTO",
    cmcId: 28541,
    universalToken: "JTO",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UFLOW",
    type: "crypto",
    network: "worldchain",
    address: "0xf413af1169516a3256504977b8ed0248fbd48f23",
    decimals: 18,
    symbol: "uFLOW",
    name: "Flow",
    description: "World App supports uFLOW on World Chain.",
    primaryColor: "#00EF8B",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uflow.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uflow.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uflow.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "9c6e80ad-54d7-5007-8969-8ce5419a4515",
    priceId: "FLOW",
    cmcId: 4558,
    universalToken: "FLOW",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UFLOKI",
    type: "crypto",
    network: "worldchain",
    address: "0xcb474f3dee195a951f3584b213d16d2d4d4ee503",
    decimals: 18,
    symbol: "uFLOKI",
    name: "FLOKI",
    description: "World App supports uFLOKI on World Chain.",
    primaryColor: "#F79422",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ufloki.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ufloki.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ufloki.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "70933143-b31f-5a01-9610-c11a4b0471d5",
    priceId: "FLOKI",
    cmcId: 10804,
    universalToken: "FLOKI",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UFLR",
    type: "crypto",
    network: "worldchain",
    address: "0xed1a31bb946f0b86cf9d34a1c90546ca75b091b0",
    decimals: 18,
    symbol: "uFLR",
    name: "Flare",
    description: "World App supports uFLR on World Chain.",
    primaryColor: "#E62058",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uflr.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uflr.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uflr.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "1ba6521f-068d-5790-b763-d3d04bd324a2",
    priceId: "FLR",
    cmcId: 7950,
    universalToken: "FLR",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UFIL",
    type: "crypto",
    network: "worldchain",
    address: "0xdf5913632251585a55970134fad8a774628e9388",
    decimals: 18,
    symbol: "uFIL",
    name: "Filecoin",
    description: "World App supports uFIL on World Chain.",
    primaryColor: "#0090FF",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ufil.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ufil.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ufil.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "24806a7e-94cc-5690-8544-89b840a49ff0",
    priceId: "FIL",
    cmcId: 2280,
    universalToken: "FIL",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UENS",
    type: "crypto",
    network: "worldchain",
    address: "0x8f2bd24a6406142cbae4b39e14be8efc8157d951",
    decimals: 18,
    symbol: "uENS",
    name: "Ethereum Name Service",
    description: "World App supports uENS on World Chain.",
    primaryColor: "#5298FF",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uens.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uens.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uens.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "369c985a-d070-5409-bae0-adb359a07508",
    priceId: "ENS",
    cmcId: 13855,
    universalToken: "ENS",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UWIF",
    type: "crypto",
    network: "worldchain",
    address: "0x17f8d5aa7779094c32536fecb177f93b33b3c3e2",
    decimals: 18,
    symbol: "uWIF",
    name: "dogwifhat",
    description: "World App supports uWIF on World Chain.",
    primaryColor: "#EFBFA8",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uwif.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uwif.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uwif.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "7f4ce431-2b3d-5514-b78d-188ca348c452",
    priceId: "WIF",
    cmcId: 28752,
    universalToken: "WIF",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UCRV",
    type: "crypto",
    network: "worldchain",
    address: "0x0340ff1765f0099b3bd1c4664ce03d8fd794fad1",
    decimals: 18,
    symbol: "uCRV",
    name: "Curve DAO Token",
    description: "World App supports uCRV on World Chain.",
    primaryColor: "#181818",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ucrv.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ucrv.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ucrv.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "79299e5a-8396-5610-ae69-5678afdaa3c0",
    priceId: "CRV",
    cmcId: 6538,
    universalToken: "CRV",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UCRO",
    type: "crypto",
    network: "worldchain",
    address: "0xf653e8b6fcbd2a63246c6b7722d1e9d819611241",
    decimals: 18,
    symbol: "uCRO",
    name: "Cronos",
    description: "World App supports uCRO on World Chain.",
    primaryColor: "#002D74",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ucro.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ucro.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ucro.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "1245869d-a03a-522f-8cc3-8fa5c493ce7b",
    priceId: "CRO",
    cmcId: 3635,
    universalToken: "CRO",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UTIA",
    type: "crypto",
    network: "worldchain",
    address: "0x901754d839cf91eaa3ff7cb11408750fc94174e4",
    decimals: 18,
    symbol: "uTIA",
    name: "Celestia",
    description: "World App supports uTIA on World Chain.",
    primaryColor: "#7B2BF9",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/utia.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/utia.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/utia.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "0e569a3b-336e-5140-8970-04e27f00503c",
    priceId: "TIA",
    cmcId: 22861,
    universalToken: "TIA",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UBONK",
    type: "crypto",
    network: "worldchain",
    address: "0xf56ce53561a9cc084e094952232bbfe1e5fb599e",
    decimals: 18,
    symbol: "uBONK",
    name: "Bonk",
    description: "World App supports uBONK on World Chain.",
    primaryColor: "#FDDE00",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ubonk.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ubonk.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ubonk.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "3a047ef9-2fd2-511b-848c-8c68b729c383",
    priceId: "BONK",
    cmcId: 23095,
    universalToken: "BONK",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UARB",
    type: "crypto",
    network: "worldchain",
    address: "0xd01cb4171a985571deff48c9dc2f6e153a244d64",
    decimals: 18,
    symbol: "uARB",
    name: "Arbitrum",
    description: "World App supports uARB on World Chain.",
    primaryColor: "#213147",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uarb.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uarb.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uarb.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "a6e4975f-c4ed-5254-b7a4-14b9aec1db4f",
    priceId: "ARB",
    cmcId: 11841,
    universalToken: "ARB",
    since: "2.9.306",
    traits: { transferable: {} },
  },
  {
    asset: "U1INCH",
    type: "crypto",
    network: "worldchain",
    address: "0x3c07ef1bd575b5f5b1ffcb868353f5bc501ed482",
    decimals: 18,
    symbol: "u1INCH",
    name: "1inch",
    description: "World App supports u1INCH on World Chain.",
    primaryColor: "#1C324F",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/u1inch.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/u1inch.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/u1inch.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "ce2e8d85-0322-5aa6-9066-4c794478107d",
    priceId: "1INCH",
    cmcId: 8104,
    universalToken: "1INCH",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UTAO",
    type: "crypto",
    network: "worldchain",
    address: "0xfdca15bd55f350a36e63c47661914d80411d2c22",
    decimals: 18,
    symbol: "uTAO",
    name: "Bittensor",
    description: "World App supports uTAO on World Chain.",
    primaryColor: "#000000",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/utao.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/utao.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/utao.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "661f62bf-7e93-5c14-9fe6-71383e2d1e4e",
    priceId: "TAO",
    cmcId: 22974,
    universalToken: "TAO",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UPENGU",
    type: "crypto",
    network: "worldchain",
    address: "0xdef3369cb0b783a5f8ee93aaf9674dde53c3ce2a",
    decimals: 18,
    symbol: "uPENGU",
    name: "Pudgy Penguins",
    description: "World App supports uPENGU on World Chain.",
    primaryColor: "#8DB4FD",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/upengu.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/upengu.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/upengu.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "75e0dde7-7db3-535e-a0a1-9dac12850db3",
    priceId: "PENGU",
    priceSince: new Date("2024-12-17T14:00:00.000Z"),
    cmcId: 34466,
    universalToken: "PENGU",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UIP",
    type: "crypto",
    network: "worldchain",
    address: "0xf081701af06a8d4ecf159c9c178b5ca6a78b5548",
    decimals: 18,
    symbol: "uIP",
    name: "Story Protocol",
    description: "World App supports uIP on World Chain.",
    primaryColor: "#D7B64B",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uip.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uip.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uip.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "bc47bb0f-4d69-5668-bb4a-12179e8420fb",
    priceId: "IP",
    priceSince: new Date("2025-02-06T07:02:40.000Z"),
    cmcId: 35626,
    universalToken: "IP",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UBNB",
    type: "crypto",
    network: "worldchain",
    address: "0x91b1b343ac321c0579ed33854e20a98ef881cc89",
    decimals: 18,
    symbol: "uBNB",
    name: "BNB",
    description: "World App supports uBNB on World Chain.",
    primaryColor: "#F0B90B",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ubnb.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ubnb.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ubnb.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "02a5e333-5e16-5500-af60-0bd3850ad657",
    priceId: "BNB",
    cmcId: 1839,
    universalToken: "BNB",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UWLFI",
    type: "crypto",
    network: "worldchain",
    address: "0xab1f3295c2cf4ea971170cfb1430a933f18bc455",
    decimals: 18,
    symbol: "uWLFI",
    name: "World Liberty Financial Price",
    description: "World App supports uWLFI on World Chain.",
    primaryColor: "#E7AC08",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uwlfi.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uwlfi.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uwlfi.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "fc50c651-c8c4-5afa-bfd1-bd8b533f74b0",
    priceId: "WLFI",
    cmcId: 33251,
    universalToken: "WLFI",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UPAXG",
    type: "crypto",
    network: "worldchain",
    address: "0xdcc74175fb91f84326a95922ad4d95d1a20cd559",
    decimals: 18,
    symbol: "uPAXG",
    name: "PAX Gold Price",
    description: "World App supports uPAXG on World Chain.",
    primaryColor: "#CCA727",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/upaxg.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/upaxg.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/upaxg.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "91535eae-11c1-57c5-867b-81d7f46e4331",
    priceId: "PAXG",
    cmcId: 4705,
    universalToken: "PAXG",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UMON",
    type: "crypto",
    network: "worldchain",
    address: "0x8c655ca4fe20c089d7d6823afd17ed6a377296e3",
    decimals: 18,
    symbol: "uMON",
    name: "Monad",
    description: "World App supports uMON on World Chain.",
    primaryColor: "#020719",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/umon.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/umon.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/umon.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "bcd442bd-62e8-5eb4-a4e4-3e0602c738d0",
    priceId: "MON",
    cmcId: 30495,
    universalToken: "MON",
    priceSince: new Date("2025-11-25T00:00:00.000Z"),
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UCOMP",
    type: "crypto",
    network: "worldchain",
    address: "0xede6b57341c88652e5970229bd84fc316db1c85d",
    decimals: 18,
    symbol: "uCOMP",
    name: "Compound",
    description: "World App supports uCOMP on World Chain.",
    primaryColor: "#00D395",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ucomp.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ucomp.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ucomp.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "b09e954c-a118-578c-8876-cc35f2c87cd6",
    priceId: "COMP",
    cmcId: 5692,
    universalToken: "COMP",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UETHFI",
    type: "crypto",
    network: "worldchain",
    address: "0x3c569273572706380785e079c8bc16df6a31bc51",
    decimals: 18,
    symbol: "uETHFI",
    name: "Ether.fi",
    description: "World App supports uETHFI on World Chain.",
    primaryColor: "#0C1467",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uethfi.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uethfi.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uethfi.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "35fe624e-aa25-5ce6-81dc-aa667e6724c0",
    priceId: "ETHFI",

    cmcId: 29814,
    universalToken: "ETHFI",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UBERA",
    type: "crypto",
    network: "worldchain",
    address: "0x544f87a5aa41fcd725ef7c78a37cd9c1c4ba1650",
    decimals: 18,
    symbol: "uBERA",
    name: "Berachain",
    description: "World App supports uBERA on World Chain.",
    primaryColor: "#0C1467",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ubera.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ubera.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ubera.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "1f7868dd-dd71-50c9-b325-71a317897ac0",
    priceId: "BERA",
    cmcId: 24647,
    priceSince: new Date("2025-02-07T00:00:00.000Z"),
    universalToken: "BERA",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UREZ",
    type: "crypto",
    network: "worldchain",
    address: "0x12a063bef460bea2b4d0b504bd78bba58fb3da7e",
    decimals: 18,
    symbol: "uREZ",
    name: "Renzo",
    description: "World App supports uREZ on World Chain.",
    primaryColor: "#0C1467",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/urez.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/urez.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/urez.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "80da95c7-50c3-53b2-a9ad-7a2e578eea40",
    priceId: "REZ",
    cmcId: 30843,
    universalToken: "REZ",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UALEO",
    type: "crypto",
    network: "worldchain",
    address: "0xa2fd26586610955955b9a6e4be477433224a35bf",
    decimals: 18,
    symbol: "uALEO",
    name: "Aleo",
    description: "World App supports uALEO on World Chain.",
    primaryColor: "#0C1467",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ualeo.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ualeo.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ualeo.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "a8e42fca-56c2-5220-b9c3-b600cb9060d2",
    priceId: "ALEO",
    cmcId: 32193,
    universalToken: "ALEO",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UZRO",
    type: "crypto",
    network: "worldchain",
    address: "0xf5c9e46a87093fb29e40a9e498b078058bbadc74",
    decimals: 18,
    symbol: "uZRO",
    name: "LayerZero",
    description: "World App supports uZRO on World Chain.",
    primaryColor: "#0C1467",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uzro.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uzro.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uzro.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "0ad04477-5148-5702-af6c-9dc4f622ee79",
    priceId: "ZRO",
    cmcId: 26997,
    universalToken: "ZRO",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "URON",
    type: "crypto",
    network: "worldchain",
    address: "0xdbbc41ffd1e4d219e2cfd5bfe9e4623cd4274532",
    decimals: 18,
    symbol: "uRON",
    name: "Ronin",
    description: "World App supports uRON on World Chain.",
    primaryColor: "#0C1467",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uron.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uron.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uron.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "0dd11b6d-8c2f-58bc-b6e1-e2495a037090",
    priceId: "RON",
    cmcId: 14101,
    universalToken: "RON",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UAKT",
    type: "crypto",
    network: "worldchain",
    address: "0xba0020a82be4df8f5eafb5bf6e173ee792d1920b",
    decimals: 18,
    symbol: "uAKT",
    name: "Akash",
    description: "World App supports uAKT on World Chain.",
    primaryColor: "#1A0002",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uakt.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uakt.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uakt.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "7eccd007-5fe7-524b-99e7-6d8243788714",
    priceId: "AKT",
    cmcId: 7431,
    universalToken: "AKT",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UCVX",
    type: "crypto",
    network: "worldchain",
    address: "0x7047865f343a616187d05ef860530805bdc2fa42",
    decimals: 18,
    symbol: "uCVX",
    name: "Convex Finance",
    description: "World App supports uCVX on World Chain.",
    primaryColor: "#3A3A3A",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ucvx.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ucvx.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ucvx.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "de9de650-955f-5bb2-9ad0-b61efb05b2f4",
    priceId: "CVX",
    cmcId: 9903,
    universalToken: "CVX",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UENA",
    type: "crypto",
    network: "worldchain",
    address: "0x4aae3050089658ee70d7e202bb06b739526f0177",
    decimals: 18,
    symbol: "uENA",
    name: "Ethena",
    description: "World App supports uENA on World Chain.",
    primaryColor: "#2E2E2E",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uena.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uena.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/uena.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "7d721c8e-5357-5c21-b716-d4751acfba73",
    priceId: "ENA",
    cmcId: 30171,
    universalToken: "ENA",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "USYRUP",
    type: "crypto",
    network: "worldchain",
    address: "0x2f15a6d380473f2a90519802c6b8635329aa6c50",
    decimals: 18,
    symbol: "uSYRUP",
    name: "Maple Finance",
    description: "World App supports uSYRUP on World Chain.",
    primaryColor: "#F57547",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/usyrup.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/usyrup.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/usyrup.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "caed44ea-585c-5893-93fd-8b701626a760",
    priceId: "SYRUP",
    cmcId: 33824,
    universalToken: "SYRUP",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UFARTCOIN",
    type: "crypto",
    network: "worldchain",
    address: "0x6a2ed50496495f087cac3ae1aea3d540ad79ef28",
    decimals: 18,
    symbol: "uFARTCOIN",
    name: "Fartcoin",
    description: "World App supports uFARTCOIN on World Chain.",
    primaryColor: "#000000",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ufartcoin.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ufartcoin.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/ufartcoin.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "4f0cb7a4-684a-5cc6-b88b-c91c5f181f5a",
    priceId: "FARTCOIN",
    cmcId: 33597,
    universalToken: "FARTCOIN",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UPUMP",
    type: "crypto",
    network: "worldchain",
    address: "0x20fbd133897ef802e0235db77bb19a071e257d41",
    decimals: 18,
    symbol: "uPUMP",
    name: "Pump.fun",
    description: "World App supports uPUMP on World Chain.",
    primaryColor: "#67C18E",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/upump.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/upump.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/upump.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "c6b7e878-862e-5a45-9126-fdf74517f341",
    priceId: "PUMP",
    cmcId: 36507,
    universalToken: "PUMP",
    since: "2.9.500",
    traits: { transferable: {} },
  },
  {
    asset: "UMSOL",
    type: "crypto",
    network: "worldchain",
    address: "0x7383e814cf15fa06373654e6dd121d0d3b4f9e51",
    decimals: 18,
    symbol: "uMSOL",
    name: "Marinade Staked SOL",
    description: "World App supports uMSOL on World Chain.",
    primaryColor: "#4B8D8B",
    secondaryColor: "#000000",
    icon: "https://static.app-backend.worldcoin.dev/assets/crypto/v2/umsol.png",
    iconHexa:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/umsol.png",
    iconHexaV2:
      "https://static.app-backend.worldcoin.dev/assets/crypto/v2/umsol.png",
    issuerId: AssetIssuerId.Universal,
    dbId: "173813fc-8229-5996-aa36-268e140151ca",
    priceId: "MSOL",
    cmcId: 11461,
    universalToken: "MSOL",
    since: "2.9.500",
    traits: { transferable: {} },
  },
];
